Feature/signin
f-lab-edu/AtoZ pull request #10
Opened 2022-11-27 11:37 UTC by ksjeong761

2022-12-04 14:54 UTC, Joel-FLab requested changes
전반적으로 테스트가 많이 정리되어 보기 좋네요! 다만 주석은 반드시 알아야하는 히스토리나 알고리즘에 담기지 않는 내용만을 적고, 메서드명이나 변수명을 통해서 가독성을 최대한 높이는 쪽으로 작성하는 방향이 유지보수 부담을 줄여주기 때문에 현재 남아있는 주석 대부분은 지워도 좋을것 같아요. 로직은 몇 군데 수정이 필요해보여요!

2022-12-04 14:54 UTC, Joel-FLab commented on src/main/java/com/atoz/security/SecurityConfig.java
> +        return new DelegatingPasswordEncoder(idForEncode, encoders);
new Argon2PasswordEncoder()하지 않고 따로 map을 만들어서 빌드하신 이유가 있을까요?

2022-12-04 14:54 UTC, Joel-FLab commented on src/main/java/com/atoz/security/authentication/AuthenticationServiceImpl.java
> +        return provideToken(authentication);
메서드에서 동작이 다 드러나기 때문에 주석은 지워도 될 것 같아요!

2022-12-04 14:54 UTC, Joel-FLab commented on src/main/java/com/atoz/security/authentication/AuthenticationServiceImpl.java
> +        refreshTokenMapper.deleteToken(authentication.getName());
로그아웃하는데는 인증만 필요하지 않을까요? 마찬가지로 주석은 지워도 될 것 같아요.

2022-12-04 14:54 UTC, Joel-FLab commented on src/main/java/com/atoz/security/authentication/AuthenticationServiceImpl.java
> +
메서드 이름에서 최대한 동작이 드러나게하고, 주석은 정말 필요한 경우에만 적는 것이 좋아요. 이런 경우에는 updateTokens 같은 메서드명을 사용하면 동작이 드러날 것 같아요.

2022-12-04 14:54 UTC, Joel-FLab commented on src/main/java/com/atoz/security/authorization/JwtAuthorizationFilter.java
> +
이렇게하면 user관련 요청도 인증 정보를 확인하지 않게 될 것 같은데,, 이거 의도하신건가요?

2022-12-04 14:54 UTC, Joel-FLab commented on src/main/java/com/atoz/security/authorization/JwtAuthorizationProvider.java
> +        }
리프레시 토큰이 없다 = 로그아웃된 사용자다 라고 봐도 될까요? 이건 궁금해서 코멘트해요!

2022-12-04 14:54 UTC, Joel-FLab commented on src/main/java/com/atoz/security/token/TokenParser.java
> +     */
이 주석도 불필요해보여요!

2022-12-04 14:54 UTC, Joel-FLab commented on src/main/java/com/atoz/security/token/TokenProviderImpl.java
> +            @Value("${jwt.refresh-token-expire-time}") long refreshTime) {
이렇게하면 application.yml에 값이 없으면 어떻게 되나요? null이나 0으로 바인딩되면 문제가 되지 않을까요?

2022-12-04 14:54 UTC, Joel-FLab commented on src/test/java/com/atoz/security/authentication/AuthenticationControllerTest.java
>                  .defaultResponseCharacterEncoding(StandardCharsets.UTF_8)
DummyAuthenticationService가 Dummy의 역할을 하고 있나요? API호출하면 메서드가 호출될 것 같은데 그러면 Dummy로 사용되는게 아닌것 같아요!

2022-12-04 14:54 UTC, Joel-FLab commented on src/test/java/com/atoz/security/authorization/JwtAuthorizationFilterTest.java
> +
이런건 따로 상수클래스를 만들어서 서비스와 테스트 둘 다에서 참조해도 될 것 같아요.

2022-12-04 14:54 UTC, Joel-FLab commented on src/test/java/com/atoz/user/UserMapperTest.java
> +        sut.addAuthority(signedUpUser);
이렇게하면 addUser와 addAuthority를 테스트하기도 전에 setup에서 이미 호출하게 되는데, 필요할때마다 테스트케이스에서 넣는게 맞을 것 같아요!

2022-12-05 06:37 UTC, ksjeong761 commented on src/main/java/com/atoz/security/authorization/JwtAuthorizationFilter.java
> +
의도된 동작이 맞습니다.
회원가입에 user 경로를 사용하고, user 경로를 사용하는 다른 기능이 아예 없었으니까요.

지금은 사용자 정보 수정, 회원 탈퇴 기능을 추가하면서
/user/signup처럼 좀 더 구체적인 경로로 수정한 상태입니다.

또한 URL 경로 체크를 필터 체인과 필터에서 중복으로 하고 있으므로
필터 체인에서만 경로를 구분하게 하여 해당 코드를 제거했습니다.

2022-12-05 06:44 UTC, ksjeong761 commented on src/main/java/com/atoz/security/authorization/JwtAuthorizationProvider.java
> +        }
현재로선 그렇습니다.
DB에 저장된 리프레시 토큰이 없다면 로그인을 할 수가 없으므로
세션과 비슷한 방식으로 동작하고 있습니다.

JWT를 제대로 활용하지 못하고 있는 것 같아서
권한 부여 쪽을 구현하면서 이 부분도 같이 수정하려고 생각하고 있습니다.

2022-12-05 07:01 UTC, ksjeong761 commented on src/test/java/com/atoz/security/authentication/AuthenticationControllerTest.java
>                  .defaultResponseCharacterEncoding(StandardCharsets.UTF_8)
null을 반환하도록 구현해서 Dummy라고 이름 붙였는데
메서드 호출 자체가 되면 안 되는 걸 빼먹었네요 ㅎㅎ..
Stub으로 이름을 바꿔야겠습니다

2022-12-05 07:11 UTC, ksjeong761 commented on src/main/java/com/atoz/security/SecurityConfig.java
> +        return new DelegatingPasswordEncoder(idForEncode, encoders);
DelegatingPasswordEncoder를 써서 나중에 좀 더 유연하게
인코딩 알고리즘을 변경할 수 있도록 하고 싶었습니다.

다시 생각해보니 굳이 처음부터 적용할 필요 없이 나중에 필요해졌을 때
이 클래스로 기존 인코딩 방식을 포함하도록 구현하면 되겠네요~

2022-12-05 07:17 UTC, ksjeong761 commented on src/main/java/com/atoz/security/token/TokenProviderImpl.java
> +            @Value("${jwt.refresh-token-expire-time}") long refreshTime) {
확실히 문제가 생기겠네요...
기본 값을 줘버리면 파일에서 읽어오는 의미도 없어지는 게 아닌가 해서 놔뒀는데 수정해야겠습니다.
생성자에서 값 넣는 것도 테스트 코드가 지저분해져서 분리하고 싶었는데 이 참에 한번 시도해봐야겠네요~

2022-12-07 12:57 UTC, merged