[#8] 회원 정보 수정, 탈퇴 기능 추가
f-lab-edu/AtoZ pull request #14
Opened 2022-12-08 06:46 UTC by ksjeong761

2022-12-11 12:11 UTC, Joel-FLab requested changes
몇 가지 질문과 변경 요청 남겼습니다!

2022-12-11 12:11 UTC, Joel-FLab commented on src/test/java/com/atoz/user/UserControllerTest.java
>          this.sut = MockMvcBuilders
전부 this를 붙이거나, 전부 붙이지 않거나 하는 일관성이 있으면 좋을 것 같아요.

2022-12-11 12:11 UTC, Joel-FLab commented on src/test/java/com/atoz/user/UserControllerTest.java
> +        signupRequest.put("email", "test@test.com");
DTO를 사용하지 않고 Map을 사용하는 이유가 있을까요?

2022-12-11 12:11 UTC, Joel-FLab commented on src/test/java/com/atoz/user/UserControllerTest.java
> +    }
어떤 내용을 테스트하고 싶은지 명확해보이지 않는 것 같아요. 요청이 성공하기만 하면 될까요? 사용자가 삭제된 걸 확인하는게 더 의미가 있지 않을까 싶어요.

2022-12-11 12:11 UTC, Joel-FLab commented on src/test/java/com/atoz/user/UserMapperTest.java
> +    }
'비밀번호 변경'에 대한 내용에 대한 단위테스트에서 addUser와 addAuthority가 함께 호출되는게 바람직하지 않아보여요. 사용자 정보를 저장하는 것을 다른 메서드로 추출하거나 setup에 작성하는것이 가독성이 좀 더 좋지 않을까요?

2022-12-11 12:11 UTC, Joel-FLab commented on src/test/java/com/atoz/user/UserMapperTest.java
> +    }
이것도 마찬가지로 사용자 정보를 저장하는 내용을 다른 메서드나 setup으로 위임하는 것이 좋아보여요.

2022-12-11 12:11 UTC, Joel-FLab commented on src/test/java/com/atoz/user/UserServiceImplTest.java
> +
'만료된다'라는 말이 테스트를 정확히 대변해주지 않는 것 같아요. 만료된다는 토큰의 유효기간이 만료된다는 의미같아서 여기는 오히려 리프레시 토큰이 삭제된다가 정확한 의미가 아닐까요?

2022-12-11 12:11 UTC, Joel-FLab commented on src/main/java/com/atoz/user/UserController.java
>          return userService.signup(userEntity);
응답 DTO는 responseDTO로 명시되어 있는데 요청 DTO는 request로 명시되지 않은 이유가 있을까요? request로 명시해주는게 좀 더 혼동의 여지를 줄일 수 있는 방법 같아요.

2022-12-12 04:59 UTC, ksjeong761 commented on src/test/java/com/atoz/user/UserControllerTest.java
>          this.sut = MockMvcBuilders
전부 this를 붙이는 쪽으로 변경하여 멤버 변수라는 것을 명시하도록 해야겠습니다.

2022-12-12 05:03 UTC, ksjeong761 commented on src/test/java/com/atoz/user/UserControllerTest.java
> +        signupRequest.put("email", "test@test.com");
Postman으로 테스트할 때처럼 JSON 문자열을 직접 보내는 식으로 테스트 하려고 했었습니다.
어차피 ObjectMapper에 의해 변환된 JSON 문자열이 전송되니 큰 의미가 없네요.
DTO를 사용하는 방식으로 변경해야겠습니다.

2022-12-12 05:11 UTC, ksjeong761 commented on src/test/java/com/atoz/user/UserControllerTest.java
> +    }
테스트 더블인 StubUserService는 null을 반환하고 아무 동작도 하지 않으므로
현재 Controller에서는 요청에 대한 테스트밖에 할 수 없습니다.

삭제된 것을 확인하려면 테스트용 저장/삭제 코드를 직접 만들고
그 테스트용 코드를 테스트하게 되므로 실제 코드에 대한 테스트가 아니게 될 것 같습니다.

2022-12-12 05:12 UTC, ksjeong761 commented on src/test/java/com/atoz/user/UserMapperTest.java
> +    }
다른 메서드로 추출하는 방식으로 변경해보겠습니다.

2022-12-12 05:19 UTC, ksjeong761 commented on src/test/java/com/atoz/user/UserServiceImplTest.java
> +
확실히 명확하지 않게 느껴지네요. 삭제한다는 표현으로 변경하겠습니다.

2022-12-12 05:22 UTC, ksjeong761 commented on src/main/java/com/atoz/user/UserController.java
>          return userService.signup(userEntity);
변수명이 너무 길어지는 걸 경계했었습니다.
DTO 종류가 많아지다 보니 슬슬 헷갈리기 시작해서 request를 붙이도록 하겠습니다.

2022-12-12 08:00 UTC, ksjeong761 commented on src/test/java/com/atoz/user/UserControllerTest.java
>          this.sut = MockMvcBuilders
this를 싹 다 붙이니까 코드가 너무 장황해지네요.
변수명이 겹치거나 어디에 있는 변수인지 구별하기 어렵지 않다면 this를 빼는 편이 좋은 것 같습니다.

2022-12-12 14:07 UTC, merged