[#12] 게시판 추가
f-lab-edu/AtoZ pull request #15
Opened 2022-12-10 09:18 UTC by ksjeong761

2022-12-11 14:22 UTC, Joel-FLab requested changes
몇 가지 질문과 변경 요청 드렸어요!

2022-12-11 14:22 UTC, Joel-FLab commented on src/main/java/com/atoz/post/PostController.java
> +
지금 create의 의미에 PUT을 사용하고, update에 PATCH를 사용했는데, AddPost가 왜 post 요청이 아니고 put 요청인가요?

2022-12-11 14:22 UTC, Joel-FLab commented on src/main/java/com/atoz/post/PostMapper.java
> +    PostEntity findById(PostEntity postEntity);
지금 MyBatis를 사용하고 있는 상황에서 entity라는 네이밍은 JPA에서 사용하는 네이밍이기 때문에 혼동의 여지가 있을 것 같아요. DTO 정도가 맞을 것 같아요. Entity는 Jpa를 적용해서 Jpa Entity를 사용하게 될때 거기에 적용하는게 더 명확할거에요.

2022-12-11 14:22 UTC, Joel-FLab commented on src/main/java/com/atoz/post/PostController.java
> +    }
이전 PR에서와 마찬가지로 request를 위한 DTO라면 requestDTO로 명명하는게 클래스 구조 측면에서 더 알아보기 쉬울 것 같아요. 그리고 지금 PostEntity 타입을 리턴하도록 구현했는데, Entity는 Jpa에서 사용하는 테이블 매핑 구조 클래스이고, 엔드포인트에서 Entity를 리턴하는건 안티패턴이에요. 지금은 Jpa를 사용하고 있지 않기 때문에 entity라는 네이밍은 다른 것으로 변경하고, response용 DTO를 따로 작성하는 것이 바람직할 것 같아요.

2022-12-11 14:22 UTC, Joel-FLab commented on src/test/java/com/atoz/post/PostControllerTest.java
> +    private final ObjectMapper objectMapper = new ObjectMapper();
MockMvc에 private이 빠진 것 같아요.

2022-12-11 14:22 UTC, Joel-FLab commented on src/test/java/com/atoz/post/PostControllerTest.java
> +
단위테스트에서 request에 Map을 사용하고 key를 하드코딩하신 이유가 있을까요?

2022-12-11 14:22 UTC, Joel-FLab commented on src/test/java/com/atoz/post/PostMapperTest.java
> +        userMapper.addAuthority(signedUpUser);
아마 이전 PR에서 리뷰를 드렸어야 할 것 같긴한데, mapper단에서 addAuthority가 signedUpUser를 받는게 좀 어색해보이네요. updateUser를 사용하지 않고 addAuthority 메서드를 따로 만들어서 권한 정보만을 업데이트할거라면 signedUpUser가 아니라 userId와 권한 정보만을 파라미터로 받는게 좀 더 가독성이 낫지 않을까 추천드립니다.

2022-12-11 14:22 UTC, Joel-FLab commented on src/test/java/com/atoz/post/PostMapperTest.java
> +                .updatedAt(addedTime)
createdAt과 updatedAt은 DB에서 자동으로 생성일시와 업데이트일시로 들어가도록 설정할 수 있어요. `datetime default current_timestamp` 키워드로 검색해보시기를 추천드려요. 그렇게 설정하면 이렇게 어플리케이션에서 따로 넣어주지 않아도 되도록 구현할 수 있어요.

2022-12-11 14:22 UTC, Joel-FLab commented on src/test/java/com/atoz/post/PostMapperTest.java
> +                .viewCount(0)
DB에서 default 값을 0으로 주면 되지않을까요? 그렇게하면 어플리케이션 코드를 좀 더 간결하게 작성할 수 있을 것 같아요.

2022-12-11 14:22 UTC, Joel-FLab commented on src/test/java/com/atoz/post/PostMapperTest.java
> +        sut.findById(post);
이 테스트에는 assert가 없네요!

2022-12-11 14:22 UTC, Joel-FLab commented on src/test/java/com/atoz/post/PostMapperTest.java
> +        assertNull(foundPost);
테스트 가독성 측면에서 지금 sut의 메서드가 여러 개 호출되는 것 처럼 보이기 때문에 sut.addPost는 메서드로 빼거나 setup으로 올리는것을 추천드립니닷

2022-12-11 14:22 UTC, Joel-FLab commented on src/test/java/com/atoz/post/PostServiceTest.java
> +    }
시큐리티가 적용된 곳을 테스트하는 트릭이 있는데, 이를 지원해주는 어노테이션들이 있어요. https://tecoble.techcourse.co.kr/post/2020-09-30-spring-security-test/ 이 글을 한 번 참고해보시고, 좀 더 검색해보셔도 좋을 것 같아요.

2022-12-12 05:41 UTC, ksjeong761 commented on src/main/java/com/atoz/post/PostController.java
> +
POST를 막 쓰면 안 된다는 강박 때문에 막상 POST를 써야 할 곳에 PUT을 써버렸네요...
HTTP 메서드도 다시 한 번 공부해야겠습니다.

2022-12-12 05:46 UTC, ksjeong761 commented on src/main/java/com/atoz/post/PostMapper.java
> +    PostEntity findById(PostEntity postEntity);
DB 접근에 쓸만한 이름이 저것만한 게 없긴 한데.. 적절한 이름을 찾아봐야겠네요.

2022-12-12 06:17 UTC, ksjeong761 commented on src/main/java/com/atoz/post/PostController.java
> +    }
ResponseDTO로 데이터를 가공해서 응답하도록 변경하겠습니다.

2022-12-12 06:17 UTC, ksjeong761 commented on src/test/java/com/atoz/post/PostControllerTest.java
> +
Postman으로 테스트할 때처럼 JSON 문자열을 직접 보내는 식으로 테스트 하려고 했었습니다.
어차피 ObjectMapper에 의해 변환된 JSON 문자열이 전송되니 큰 의미가 없네요.
DTO를 사용하는 방식으로 변경해야겠습니다.

2022-12-12 06:18 UTC, ksjeong761 commented on src/test/java/com/atoz/post/PostMapperTest.java
> +        userMapper.addAuthority(signedUpUser);
Authority 자체를 Users 테이블에 합치는 걸 고민 중입니다.
일단은 파라미터를 변경하는 게 우선이겠네요.

2022-12-12 06:20 UTC, ksjeong761 commented on src/test/java/com/atoz/post/PostMapperTest.java
> +        sut.findById(post);
자잘한 실수가 많네요 ㄷㄷ 추가하겠습니다

2022-12-12 06:23 UTC, ksjeong761 commented on src/test/java/com/atoz/post/PostMapperTest.java
> +        assertNull(foundPost);
메서드로 빼서 이름 붙이는 게 명확해보이니 메서드로 만들도록 하겠습니다.

2022-12-12 06:29 UTC, ksjeong761 commented on src/test/java/com/atoz/post/PostServiceTest.java
> +    }
이런 방법이 있었네요 한번 적용해보겠습니다~

2022-12-12 14:11 UTC, merged