[#2] 회원가입 기능 구현
f-lab-edu/AtoZ pull request #4
Opened 2022-10-28 19:35 UTC by ksjeong761

2022-10-31 12:33 UTC, Joel-FLab requested changes
몇 가지 질문과 몇 가지 변경 제안드렸습니다 ㅎㅎ

2022-10-31 12:33 UTC, Joel-FLab commented on pom.xml
> +		</dependency>
spring-boot-starter-aop 대신에 aspectj를 사용하셨군요. aspectj를 사용하신 이유가 있을까요?

2022-10-31 12:33 UTC, Joel-FLab commented on src/main/java/com/atoz/ControllerExceptionAdvice.java
> +        log.info("ControllerExceptionAdvice validationFailed");
리턴타입이 ResponseEntity<Object>인데, Object를 그대로 두는건 너무 광범위해서, 실제로 어떤 타입이 리턴되는지 직관적으로 보이지 않는 문제가 있어요. 실수로 다른 객체를 넘겨줘도 컴파일상에서 문제가 없는 것도 위험하구요. 물론 이 경우에는 단위테스트에서 검증이 되겠지만 Object 말고 구체적인 리턴타입으로 변경하기를 제안드려요. 어차피 GlobalAdvice니까 error response에 대한 클래스를 하나 작성하고 errorMessage 프로퍼티를 두는 것은 어떨까요?

그리고 이렇게 로그를 남기면 로그로 파악할 수 있는 정보가 너무 부족하지 않을까요? 400 에러메시지로 이미 어떤 값에 대한 validation이 실패했는지는 확인할 수 있으니 이 로깅은 지우거나 추후 꼭 필요하다면 추가 정보를 덧붙이는게 좋아보여요 ㅎㅎ

2022-10-31 12:33 UTC, Joel-FLab commented on src/main/java/com/atoz/user/User.java
> +    @Size(min = 1, max = 20, message = "닉네임은 1 ~ 20자 이여야 합니다.")
Size 어노테이션이 붙어있고, min 값이 1이라면 NotBlank 어노테이션이 필요할까요?

2022-10-31 12:33 UTC, Joel-FLab commented on src/test/java/com/atoz/user/UserControllerTest.java
> -    private UserController userController;
단위테스트는 가능한 한 피드백 속도가 빨라야해요. 지금 이 Controller를 단위테스트 할 때는 bean이 로드될 필요가 없어보이는데, WebMvcTest와 Autowired, MockBean 같은 spring bean 어노테이션은 전부 제거하고 pojo 형태로 테스트를 작성해보시겠어요? MockMvcBuilders.standaloneSetup으로도 충분할거에요. 그리고 ObjectMapper는 굳이 bean으로 사용하지 않으셔도 괜찮을 것 같아요!

2022-10-31 12:33 UTC, Joel-FLab commented on src/test/java/com/atoz/user/UserControllerTest.java
> +        Map<String, String> userData = new HashMap<>();
일반적으로 사용되는 단위테스트의 네이밍 규칙에는 여러 가지가 있는데, 보통 메서드명_테스트내용_기대결과 를 서술적으로 작성해요. 서술적이라 함은 문장 형태입니다. 예컨대 여기서는 메서드명이 api명이 되고, register_회원가입이_가능해야한다 가 하나의 예시가 될 수 있겠네요.

2022-10-31 12:33 UTC, Joel-FLab commented on src/main/java/com/atoz/user/User.java
> +
이 클래스는 request를 받기위한 목적으로 작성되었기 때문에 UserRequestDTO 같은 네이밍으로 변경하는 것을 제안드려요! UserEntity, UserResponseDTO같이 User와 관련된 객체가 점점 많아질 거라서 용도를 확실히 알 수 있는 네이밍이 좋습니다.

2022-10-31 12:33 UTC, Joel-FLab commented on src/main/java/com/atoz/user/UserController.java
> +    public ResponseEntity<User> register(@Validated @RequestBody User user) {
RestController 어노테이션을 붙였기 때문에 ResponseEntity가 아니라 그냥 User 객체를 리턴하더라도 200 OK로 응답이 내려갈거에요. 코드의 중복을 제거하는 것이 리팩토링의 기본이기 때문에 RestController에서 정상응답인 경우에는 ResponseEntity를 제외하시기를 제안드려요.

2022-10-31 12:33 UTC, Joel-FLab commented on src/main/java/com/atoz/user/UserController.java
이 로깅의 경우에는 회원이 많아지는 경우에 큰 의미 없이 로그가 쌓여서 다른 중요한 로그를 보기 힘들게 만들 것 같아요! 이게 꼭 필요한 로깅일까요?

2022-10-31 12:33 UTC, Joel-FLab commented on src/main/java/com/atoz/user/UserController.java
>      }
UserRequestDTO를 그대로 내려주는 경우에는 password 정보까지 그대로 client로 내려갑니다. UserResponseDTO를 따로 정의해서 필요한 정보만을 내려줘야해요!

2022-10-31 12:33 UTC, Joel-FLab commented on src/test/java/com/atoz/user/UserControllerTest.java
> +    }
단위테스트는 한 번에 한 가지만을 테스트하는 것이 바람직해요. 지금 이 테스트들의 경우에는 하나의 단위테스트에서 여러 가지의 조건들을 테스트하고 있기 때문에 분리하시기를 제안드려요.

2022-11-02 03:55 UTC, ksjeong761 commented on pom.xml
> +		</dependency>
AspectJ 어노테이션으로 검증 관련 횡단 관심사를 처리하는 AOP를 구현하기 위해 사용했습니다.
spring-boot-start-aop에 aspectjweaver가 포함되어 있으니 교체하는 게 좋겠네요~

2022-11-02 03:57 UTC, ksjeong761 commented on src/main/java/com/atoz/user/User.java
> +    @Size(min = 1, max = 20, message = "닉네임은 1 ~ 20자 이여야 합니다.")
NotBlack는 NotNull에 문자열이 공백인지 검사하는 부분이 추가된 것이니
Size에 min을 사용하면 필요가 없겠네요. NotNull로 교체해야겠습니다.

2022-11-02 04:02 UTC, ksjeong761 commented on src/main/java/com/atoz/user/UserController.java
Controller-Service-Mapper가 잘 호출되는지 확인하기 위한 로그였습니다.
목적은 달성했으니 지워야겠네요~

2022-11-02 11:53 UTC, merged