Feature/login
f-lab-edu/AtoZ pull request #5
Opened 2022-10-30 09:18 UTC by SangMin90

1. 코딩 컨벤션 반영 - 로그인 패키지 구조 변경
2. 피드백 반영 - Repository 삭제 및 Mapper로 대체
3. 피드백 반영 - AOP를 통한 로그인 검증 예외 로직 처리

2022-10-31 12:51 UTC, Joel-FLab requested changes
몇 가지 질문과 몇 가지 변경 요청드렸어요 ㅎㅎ

2022-10-31 12:51 UTC, Joel-FLab commented on src/main/java/com/atoz/login/ExceptionControllerAdvice.java
> +        log.info("ExceptionControllerAdvice.handleLoginValidation");
리턴타입이 ResponseEntity인데, Object를 그대로 두는건 너무 광범위해서, 실제로 어떤 타입이 리턴되는지 직관적으로 보이지 않는 문제가 있어요. 실수로 다른 객체를 넘겨줘도 컴파일상에서 문제가 없는 것도 위험하구요. 물론 이 경우에는 단위테스트에서 검증이 되겠지만 Object 말고 구체적인 리턴타입으로 변경하기를 제안드려요. 어차피 GlobalAdvice니까 error response에 대한 클래스를 하나 작성하고 errorMessage 프로퍼티를 두는 것은 어떨까요?

그리고 이렇게 로그를 남기면 로그로 파악할 수 있는 정보가 너무 부족하지 않을까요? 400 에러메시지로 이미 어떤 값에 대한 validation이 실패했는지는 확인할 수 있으니 이 로깅은 지우거나 추후 꼭 필요하다면 추가 정보를 덧붙이는게 좋아보여요 ㅎㅎ

2022-10-31 12:51 UTC, Joel-FLab commented on src/main/java/com/atoz/login/LoginController.java
> +                                        HttpServletRequest request) {
RestController 어노테이션을 붙였기 때문에 ResponseEntity가 아니라 그냥 User 객체를 리턴하더라도 200 OK로 응답이 내려갈거에요. 코드의 중복을 제거하는 것이 리팩토링의 기본이기 때문에 RestController에서 정상응답인 경우에는 ResponseEntity를 제외하시기를 제안드려요. 그리고 리턴타입이 Object인 것은 안티패턴이에요! 어떤 타입이 들어가도 컴파일타임에 에러가 나지 않기 때문에 정적타입언어의 장점을 버리는 것과 같습니다.

2022-10-31 12:51 UTC, Joel-FLab commented on src/main/java/com/atoz/login/LoginController.java
> +
로그인 할 때 이렇게 로깅을 하면 트래픽이 몰릴때 이 로그가 무의미하게 많이 쌓여서 다른 중요한 로그들을 묻어버릴 가능성이 높아요. 특별히 필요하지 않다면 이 로깅은 삭제하시기를 제안드려요.

2022-10-31 12:51 UTC, Joel-FLab commented on src/main/java/com/atoz/login/LoginInfo.java
>      private String userId;
NotNull의 에러메시지가 null과는 상관이 없어보이는데, 아이디를 반드시 입력해주세요 같은 메시지가 더 맞지 않을까요?

2022-10-31 12:51 UTC, Joel-FLab commented on src/main/java/com/atoz/login/LoginInfo.java
LoginInfo는 request를 받기 위해 사용되는 객체이기 때문에 LoginRequestDTO 같은 네이밍으로 변경하시기를 제안드려요. 비슷한 피드백을 기석님께도 드렸는데 requestDTO와 responseDTO의 네이밍 컨벤션을 정의하시고 별도의 패키지로 분리하는 것도 좋은 방법일 것 같아요.

2022-10-31 12:51 UTC, Joel-FLab commented on src/main/java/com/atoz/login/LoginInfo.java
>      private String password;
얘도 마찬가지입니다. 패스워드를 반드시 입력해주세요 같은 메시지가 더 맞지 않을까요?

2022-10-31 12:51 UTC, Joel-FLab commented on src/main/java/com/atoz/login/LoginServiceImpl.java
> +        log.info("LoginServiceImpl.getLoginInfo");
앞서 로그인 컨트롤러에서와 마찬가지로 특별히 필요하지 않다면 이 로깅은 삭제하시기를 제안드려요!

2022-10-31 12:51 UTC, Joel-FLab commented on src/test/java/com/atoz/login/LoginServiceImplTest.java
>      LoginServiceImpl loginServiceImpl;
이 정도 Mockito 없이도 충분히 테스트 할 수 있어요. mockito 없이 pojo로 테스트를 작성해보시기를 제안드려요!

2022-11-01 05:55 UTC, SangMin90 commented on src/main/java/com/atoz/login/ExceptionControllerAdvice.java
> +        log.info("ExceptionControllerAdvice.handleLoginValidation");
1. ErrorResponse 객체 생성 및 ResponseEntity 리턴타입으로 지정
    - 프로퍼티 : String errorMessage
    - 효과
        - 예외 발생 시 일관된 형태로 HTTP 응답 메시지의 바디 내용 전달합니다.
        - 따라서 클라이언트 단에서 예외 처리를 동일한 로직으로 처리할 수 있습니다.
        - ResponseEntity의 리턴타입으로 다른 객체를 집어 넣더라도 컴파일 시점에 예외 파악 가능합니다.

2. 로그 정보 추가
    - 목적
        - 로그 정보를 토대로 향후 무분별한 로그인 시 고객정보 탈취로 판단하여 IP 차단 시 활용
    - 특성
        - remoteIp : 클라이언트 IP (IPv6로 표현)
        - exception : 예외 클래스
        - errorMessage : 예외 메시지 
    - 구현 시 고려사항
        - 클라이언트의 원 IP 주소를 가져올 수 있는 경우, 보통 HttpServletRequest 클래스의 getRemoteAddr 메서드를 사용하게 됩니다.
        - 그러나 클라이언트가 로드 밸런서나 프록시 서버 등을 통해 접속하는 경우 프록시나 로드 밸런서의 IP 주소를 얻게 됩니다.
        - 따라서 X-Forwarded-For(XFF) 헤더 등을 통해 정확한 클라이언트의 IP 추출하였습니다.

2022-11-02 12:18 UTC, SangMin90 commented on src/main/java/com/atoz/login/LoginController.java
> +
단순히 인스턴스가 호출되는지 파악하기 위해 별 생각 없이 작성한 코드인데 어제 멘토링 중 얘기했던 테스트 더블 중 Spy를 통해 충분히 체크할 수 있을 것 같습니다.

#### 로그를 왜 남겨야 하는가?
    - 운영환경에 출시된 애플리케이션의 상태를 확인하고 문제 발생 시 대응하기 위해서
    - 로그를 남김으로써 발생예상치 못한 애플리케이션의 문제를 진단할 수 있고, 사용자 로그의 경우 분석 데이터로 활용할 수 있음
#### 무엇을 로그로 남겨야 하는가?
    - 트래픽 정보(request url, parameter, remote ip 등) → 외부에서 API를 호출하는 형태를 분석
    - 애플리케이션에서 외부로 호출을 한 후 받은 응답 → 외부 통신의 오류 파악
    - Error 로그
#### 로그 레벨
스프링 부트의 로깅 라이브러리인 LogBack은 5단계의 로그 레벨을 가진다. 심각도 수준은 Error > Warn > Info > Debug> Trace이다.   

    Error : 예상하지 못한 심각한 문제가 발생하는 경우, 즉시 조치를 취해야할 수준의 레벨
    Warn : 당장 서비스 운영에는 영향이 없지만 주의해야 할 부분.  예상 가능한 문제로 인한 예외 처리 등 자동복구가 가능한 것들
    Info : 운영에 참고할만한 사항. 중요한 비즈니스 프로세스의 시작과 완료 등
    Debug : 개발 단계에서 사용하며 SQL 로깅을 할 수 있음
    Trace : 모든 레벨에 대한 로깅이 추적되므로 개발 단계에서 사용함
#### 불필요한 로그를 남길 시 문제점
    - 메모리를 불필요하게 많이 사용하여 애플리케이션의 작동에 영향을 미칠 수 있음    
    - 중요한 로그가 묻힐 가능성이 높음

2022-11-02 12:23 UTC, SangMin90 commented on src/main/java/com/atoz/login/LoginServiceImpl.java
> +        log.info("LoginServiceImpl.getLoginInfo");
네! 리뷰 반영했습니다!

2022-11-02 12:38 UTC, SangMin90 commented on src/main/java/com/atoz/login/LoginInfo.java
>      private String userId;
기능 구현에만 집중하다보니 맥락을 고려하지 않았습니다
리뷰 반영했습니다!

2022-11-02 12:38 UTC, SangMin90 commented on src/main/java/com/atoz/login/LoginInfo.java
>      private String password;
리뷰 반영했습니다!

2022-11-03 04:53 UTC, SangMin90 commented on src/main/java/com/atoz/login/LoginInfo.java
네. 명칭 통일했습니다!

2022-11-03 06:47 UTC, SangMin90 commented on src/test/java/com/atoz/login/LoginServiceImplTest.java
>      LoginServiceImpl loginServiceImpl;
SpyStubLoginMapper 테스트 더블 객체를 생성하여 POJO 테스트 진행하였습니다.

2022-11-03 10:08 UTC, SangMin90 commented on src/main/java/com/atoz/login/LoginController.java
> +                                        HttpServletRequest request) {
ApiResponse 클래스 생성하여 ApiResponse의 인스턴스 자체를 반환하도록 변경하였습니다.

2022-11-03 10:28 UTC, merged