[#3] JWT 토큰 인증 방식의 로그인/로그아웃 기능 구현
f-lab-edu/AtoZ pull request #9
Opened 2022-11-14 12:19 UTC by SangMin90

## 1. 로그인
1. 클라이언트 로그인 요청
``
    POST /auth/signin  
    | body : {"userId":"?","password":"?"}
``
2. 유효한 사용자인지 검증(입력된 아이디, 비밀번호 유효성 검증, 비밀번호 일치 여부 검증) 후 accessToken 및 refreshToken 발급
## 2. 로그아웃
1. 클라이언트 로그아웃 요청
``
    DELET /auth/reissue
    | body : {"accessToken":"?", "refreshToken":"?"}  
``
2. accessToken 유효성 검증 후 refreshToken 존재 여부를 통해 이전에 로그아웃된 사용자인지 검증
3. 해당 사용자의 refreshToken 삭제
## 3. 토큰 재발행
1. accessToken 만료 시 클라이언트는 재발행 요청
``
    POST /auth/reissue
    body : {"accessToken":"?", "refreshToken":"?"}  
``
2. 서버에서 refreshToken 검증 후 refreshToken 존재 여부를 통해 이전에 로그아웃된 사용자인지 검증
3. 전달된 refreshToken과 DB에 저장된 refreshToken의 일치 여부 검증
4. accessToken 및 refreshToken 재발급

2022-11-17 07:21 UTC, Joel-FLab requested changes
고생 많으셨어요ㅠㅠ 몇 가지 변경하면 좋을 것 같은 부분이랑 궁금한 부분들을 코멘트로 남겼어요. 다음에 올리실때는 PR을 잘게 쪼개서 올려주실 수 있을까요? 엄청 기네요 @_@ 그리고 멘토링에서 말씀드렸던 것처럼 패키지 정리를 해보시고, 시간이 되시면 Filter에 대한 테스트도 한 번 작성해보세요!

2022-11-17 07:21 UTC, Joel-FLab commented on src/main/java/com/atoz/authentication/AuthController.java
> +    }
reissue가 refresh와 같은 의미로 보이는데, 그렇다면 refresh라는 용어로 통일하면 어떨까요?

2022-11-17 07:21 UTC, Joel-FLab commented on src/main/java/com/atoz/authentication/AuthMapper.java
> +}
AuthMapper는 대부분이 refresh token과 관련된 역할만 하고 있어서, refresh token과 관련된 로직만을 남기고 userInfo는 다른 클래스로 분리해도 좋을 것 같아요. 메서드 이름도 어떤건 refreshToken이 들어가 있고 어떤 건 없어서 다른 팀원이 이 클래스를 사용하면 좀 헷갈릴 수도 있지 않을까요?

클래스명을 RefreshTokenMapper로 변경하고, 메서드 이름에는 token을 넣는걸 제안드려요. 예컨대 findTokenById, saveToken, deleteToken 등으로요!

2022-11-17 07:21 UTC, Joel-FLab commented on src/main/java/com/atoz/authentication/AuthService.java
> +        authorities.add(user.getAuthority());
authentication에 데이터를 저장하고 userService를 호출하지 않도록 구현하면 어떨까요? 필요한 호출만을 하는게 더 깔끔할 것 같아서 제안드려요!

2022-11-17 07:21 UTC, Joel-FLab commented on src/main/java/com/atoz/authentication/AuthService.java
> +        }
SaveOrUpdateRefreshToken 같은 이름의 메서드로 분리하는 건 어떨까요?

2022-11-17 07:21 UTC, Joel-FLab commented on src/main/java/com/atoz/authentication/AuthService.java
> +
에러 메시지가 일관되면 좋을 것 같아요. "로그아웃된 사용자입니다" 이런 식으로요.

2022-11-17 07:21 UTC, Joel-FLab commented on src/main/java/com/atoz/authentication/AuthService.java
> +
사용자별로 authority 하나씩만 가지고 있도록 설계된걸까요? 그렇다고해도 User정보를 갖고 있는 객체가 getAuthorities 메서드를 가지고 있는것이 좋아보여요.

2022-11-17 07:21 UTC, Joel-FLab commented on src/main/java/com/atoz/authentication/CryptographyConfig.java
> +}
스프링시큐리티에서 제공하는 PasswordEncoder의 구현 내용이 여기 중복된 것 같은데,, 이렇게 하신 이유가 있을까요?

2022-11-17 07:21 UTC, Joel-FLab commented on src/main/java/com/atoz/authentication/Authority.java
> +    }
MemberAuth라는 enumeration이 있는데 다시 wrapping하신 이유가 있을까요?

2022-11-17 07:21 UTC, Joel-FLab commented on src/main/java/com/atoz/authentication/MemberAuth.java
> +
MemberAuth.ROLE_USER.name 을 사용하면 같은 이름을 지정해주지 않아도 string 값을 가져올 수 있어요!

2022-11-17 07:21 UTC, Joel-FLab commented on src/main/java/com/atoz/authentication/TokenProvider.java
> +                        .collect(Collectors.joining(",")));
auth의 경우에 리스트로 들어온 객체 그대로 저장해도 괜찮을 것 같아요!

2022-11-18 04:57 UTC, SangMin90 commented on src/main/java/com/atoz/authentication/AuthController.java
> +    }
재발급한다는 의미였는데 멘토님 말씀 듣고 보니 refresh 용어가 더 일관성 있어 보이네요. reissue에서 refresh로 용어로 변경했습니다!

2022-11-18 07:30 UTC, SangMin90 commented on src/main/java/com/atoz/authentication/AuthMapper.java
> +}
멘토님 말씀처럼 작성된 AuthMapper 인터페이스의 응집도가 떨어지네요... SOLID 원칙을 의식하면서 코드를 작성해야 할 것 같습니다!

RefreshTokenMapper 인터페이스를 새로 생성하여 refresh token과 관련된 메서드만 갖도록 수정했습니다.
그리고 findById 메서드는 User와 관련됐다고 생각하기 때문에 UserMapper 인터페이스로 이동하였습니다. 해당 메서드의 반환 타입인 JwtSigninDTO의 경우 사실상 UserEntity와 동일하기 때문에 UserEntity로 대체하였습니다.

2022-11-18 08:06 UTC, SangMin90 commented on src/main/java/com/atoz/authentication/AuthService.java
> +        authorities.add(user.getAuthority());
너무 맞는 말씀이네요 바로 고치겠습니다!!
직접 authMapper를 호출하면 되는데 불필요하게 customUserService를 거쳐서 authMapper를 호출하고 있었네요...

authMapper로 직접 호출하는 코드가 여러 곳에서 작성되었기 때문에 AuthService 내부에 getUserById 메서드로 추출했습니다!!

2022-11-18 08:23 UTC, SangMin90 commented on src/main/java/com/atoz/authentication/AuthService.java
> +        }
주석을 달긴 했지만 코드가 길어서 제가 봐도 가독성이 많이 떨어지네요

해당 코드를 saveOrUpdateRefreshToken 메서드로 추출하여 코드 작성의도를 명확화했습니다!!

2022-11-18 08:28 UTC, SangMin90 commented on src/main/java/com/atoz/authentication/AuthService.java
> +
변경했습니다!

2022-11-18 11:26 UTC, SangMin90 commented on src/main/java/com/atoz/authentication/CryptographyConfig.java
> +}
기석님과 Argon2 알고리즘을 패스워드 암호화에 사용하기로 결정한 후에 구현에 급급하여 먼저 PasswordEncoderFactories.createDelegatingPasswordEncoder를 복사해와서 default만 argon2 알고리즘으로 변경하여 사용했습니다.

사용하지 않는 다른 알고리즘을 지우고 argon2만 남겨 놓도록 변경하겠습니다!

2022-11-20 16:28 UTC, SangMin90 commented on src/main/java/com/atoz/authentication/AuthService.java
> +
MyBatis 사용이 아직 서툴러서 authority를 하나씩만 가지도록 구현했습니다.
현재 UserEntity에 Set<Authorities> authorities 변수를 추가하여 사용자별로 여러 개의 authority를 가질 수 있도록 설계하였고, @Getter 어노테이션을 통해 getAuthorities 메서드 또한 추가하였습니다!!

2022-11-20 16:32 UTC, SangMin90 commented on src/main/java/com/atoz/authentication/Authority.java
> +    }
Authority라는 클래스의 프로퍼티로 권한을 String으로 구현하는 것은 명확하지가 않아 MemberAuth라는 enumeration을 사용하도록 하였습니다.

멘토님 말씀처럼 굳이 다시 wrapping하지 않아도 Authority 자체를 enumeration으로 활용하면 될 것 같아 변경하였습니다!!

2022-11-20 16:57 UTC, SangMin90 commented on src/main/java/com/atoz/authentication/TokenProvider.java
> +                        .collect(Collectors.joining(",")));
auth의 타입인 Set<Authority> 그대로 저장하도록 구현했습니다!!

2022-11-20 17:07 UTC, SangMin90 commented on src/main/java/com/atoz/authentication/MemberAuth.java
> +
넵 변경했습니다!!

2022-11-21 07:01 UTC, merged